// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function opposite(clr) {
  var match = clr === /* White */0;
  if (match) {
    return /* Black */1;
  } else {
    return /* White */0;
  }
}

function homeRow(clr) {
  var match = clr === /* White */0;
  if (match) {
    return 7;
  } else {
    return 0;
  }
}

function pawnRow(clr) {
  var match = clr === /* White */0;
  if (match) {
    return 6;
  } else {
    return 1;
  }
}

function forward(clr) {
  var match = clr === /* White */0;
  if (match) {
    return -1;
  } else {
    return 1;
  }
}

var Color = {
  opposite: opposite,
  homeRow: homeRow,
  pawnRow: pawnRow,
  forward: forward
};

exports.Color = Color;
/* No side effect */
