// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Map = require("bs-platform/lib/js/map.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function compare(param, param$1) {
  var c = Caml_obj.caml_compare(param[0], param$1[0]);
  if (c !== 0) {
    return c;
  } else {
    return Caml_obj.caml_compare(param[1], param$1[1]);
  }
}

var Sq = {
  compare: compare
};

var SqMap = $$Map.Make(Sq);

function at(sq, board) {
  return Curry._2(SqMap.find_opt, sq, board.allPieces);
}

function inside(param) {
  var y = param[1];
  var x = param[0];
  if (0 <= x && x < 8 && 0 <= y) {
    return y < 8;
  } else {
    return false;
  }
}

function empty(param) {
  return {
          allPieces: SqMap.empty
        };
}

exports.Sq = Sq;
exports.SqMap = SqMap;
exports.at = at;
exports.inside = inside;
exports.empty = empty;
/* SqMap Not a pure module */
