// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Board$ReasonChess = require("../src/Board.bs.js");
var Movement$ReasonChess = require("../src/Movement.bs.js");

Jest.describe("Sliding", (function (param) {
        return Jest.test("diagonally", (function (param) {
                      var actual = Movement$ReasonChess.slide({
                            sq: /* tuple */[
                              4,
                              1
                            ],
                            color: /* White */0
                          }, /* tuple */[
                            1,
                            1
                          ], Board$ReasonChess.empty(/* () */0), true);
                      return Jest.Expect.toEqual(/* :: */[
                                  /* tuple */[
                                    7,
                                    4
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      6,
                                      3
                                    ],
                                    /* :: */[
                                      /* tuple */[
                                        5,
                                        2
                                      ],
                                      /* [] */0
                                    ]
                                  ]
                                ], Jest.Expect.expect(actual));
                    }));
      }));

/*  Not a pure module */
